[theme]
base = "light"
primaryColor = "#0F6CBD"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#103E73"
font = "sans serif"

[server]
headless = true

ADMIN_PASSWORD = "admin2026"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"


[ui]
hideTopBar = true
